### ISSUE TITLE
Exception retrieving COM object

### ISSUE THREAD

**Issue by trailmax** [SharpeRAD/Cake.IIS#21]
I'm hitting this exception:

> Retrieving the COM class factory for remote component with CLSID {2B72133B-3F5B-4602-8952-803546CE3344} from machine failed due to the following error: 800706ba

I'm running as admin and firewall is off. But I'm trying to configure the localhost (I'm automating my development setup).

I hit problems on trying to create AppPool:

```c#
Task("Create-Application-Pool")
    .Description("Create a ApplicationPool")
    .Does(() =>
    {
        CreatePool("MyProject.dev", new ApplicationPoolSettings()
        {
            Name = "MyProject.dev",
            IdentityType = IdentityType.LocalSystem,
        });
    });

```

where `MyProject.dev` is a domain name in `hosts` file pointing to `127.0.01`.

Anything I can do to debug?

**Comment by SharpeRAD** [comment]
I haven't personally seen this error before and have to [take your word that the firewall is off](http://stackoverflow.com/questions/21092050/comexception-when-trying-to-get-application-pools-using-servermanager), so I can only give you general advice:

1. Don't include the computer name when calling a local server.
2. Always include Username / Password when calling a remote server.

**Comment by trailmax** [comment]
Indeed, including computer name for local server was the issue. I did not realise that this was the actual address of the remote machine. Removing it worked:

```c#
        CreatePool(new ApplicationPoolSettings()
        {
            Name = "MyProject.dev",
            IdentityType = IdentityType.LocalSystem,
        });
```
