### ISSUE TITLE
IIS https cert bindinmg

### ISSUE THREAD

**Issue by generik0** [SharpeRAD/Cake.IIS#24]
Hi

I simply cannot get the IIS binding on HTTPS to add the cert.
The cert is added as a self signed and in the web hosting store.

I can find the cert in the store but set cert store and set cert hash does not result in the cert being set :-/

Any ideas?

Code snipit:
<pre><code>
var x509Store = new X509Store("WebHosting", StoreLocation.LocalMachine);
            var bindingSettings = IISBindings.Https
                .SetIpAddress("*")
                .SetHostName(string.Empty)
                .SetPort(443)
                .SetCertificateStoreName(x509Store.Name);

            x509Store.Open(OpenFlags.ReadOnly);
            var certificates = x509Store.Certificates;
            Console.WriteLine("Cert count "+ certificates.Count + " and looking for " + siteName);
            foreach(var x509 in certificates)
            {
                Console.WriteLine("Cert "+ x509.FriendlyName);
                if(x509.FriendlyName.Equals(siteName, StringComparison.InvariantCultureIgnoreCase))
                {
                    Console.WriteLine("Cert " + siteName + " found with hash " + System.Text.Encoding.UTF8.GetString(x509.GetCertHash()));
                    bindingSettings.SetCertificateHash(x509.GetCertHash);
                    break;
                }
            }

            CreateWebsite(remoteServerName, new WebsiteSettings()
            {
                Name = siteName,
                Binding = bindingSettings,
                PhysicalDirectory = outputDir,
                ApplicationPool = new ApplicationPoolSettings()
                {
                    Name = siteName
                },
                Overwrite = true
            });
            x509Store.Close();
</code></pre>

**Comment by SharpeRAD** [comment]
Your missing brackets at the end of the "GetCertHash" method call:
`bindingSettings.SetCertificateHash(x509.GetCertHash);`

You don't need any of these calls as there all defaults:
`.SetIpAddress("*")
.SetHostName(string.Empty)
.SetPort(443)`

Hostname should be "*" if its not defined.

Beyond that I would simply check if you can bind the cert using IIS built in UI as "Microsoft.Web.Administration" is really just a wrapper for IIS built in functionality.
