### ISSUE TITLE
Trying to stop website in remote IIS results in COM exception

### ISSUE THREAD

**Issue by kuskmen** [SharpeRAD/Cake.IIS#26]
Hi, I tried to stop website on my remote IIS like so:

`StopSite(serverName,siteName);` 

but this resulted in:

> An error occurred when executing task 'Default'.
> Error: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.Administration.Interop.IAppHostWritableAdminManager'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{FA7660F6-7B3F-4237
> -A8BF-ED0AD0DCBBD9}' failed due to the following error: Interface not registered (Exception from HRESULT: 0x80040155).

Do you have any idea what this can be caused from?

**Comment by SharpeRAD** [comment]
Googles first result for [Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.Administration.Interop.IAppHostWritableAdminManager'](https://forums.iis.net/t/1149274.aspx?ServerManager+OpenRemote+and+new+application+pools) sums it up nicely.

You need IIS installed on the machine your running the script from. I have added it to the troubleshooting page.

**Comment by kuskmen** [comment]
I don't know why I couldn't find that, you are right I had IIS Express on the machine running the script, and thus leading to COM exception , after installing IIS everything worked like a charm.
