### ISSUE TITLE
Add a flag for directory browsing when adding a site

### ISSUE THREAD

**Issue by Roemer** [SharpeRAD/Cake.IIS#27]
It should be possible to enable directory browsing.
See: https://docs.microsoft.com/en-us/iis/configuration/system.webserver/directorybrowse
```csharp
using(ServerManager serverManager = new ServerManager()) { 
	Configuration config = serverManager.GetWebConfiguration("Contoso");

	ConfigurationSection directoryBrowseSection = config.GetSection("system.webServer/directoryBrowse");
	directoryBrowseSection["enabled"] = true;
	directoryBrowseSection["showFlags"] = @"Date, Time, Size, Extension";

	serverManager.CommitChanges();
}
```

**Comment by SharpeRAD** [comment]
Happy to accept a PR for this.

**Comment by Roemer** [comment]
I just did one with some cleanups, if you accept that, I'll be happy to send some more PRs (including this one).

**Comment by SharpeRAD** [comment]
Please submit this as a separate PR that is inline with the existing coding style.

**Comment by SharpeRAD** [comment]
Happy to accept this as its own PR.

**Comment by Roemer** [comment]
Working on it, you can assign it to me.

**Comment by SharpeRAD** [comment]
Resolved by your merged PR 👍
