### ISSUE TITLE
Code inconsistencies / guidelines

### ISSUE THREAD

**Issue by Roemer** [SharpeRAD/Cake.IIS#29]
There are quite some inconsistencies and also different coding guidelines used.

The code should be cleaned to make further extensions easier.

I can do a PR for that.

**Comment by SharpeRAD** [comment]
I respect your right as an individual to format code any way you want in your own projects but I like regions, so NO...

**Comment by Roemer** [comment]
The problem is that it is very inconsistent. Some regions are missing, some have wrong "counts" (if i interpret the (x) correctly" and some are plain wrong named. I'm fine to keep them but it should be consistent. What about the other changes? I could agree to keep the regions but then they need to be consistend (I could do that as well).

**Comment by SharpeRAD** [comment]
Happy to discuss it, please provide examples of anything you feel is incorrectly named and suggest alternatives then we can go from there.

**Comment by Roemer** [comment]
What about the way too many newlines and small optimizations?
For the regions: can we drop the number of elements included?

**Comment by SharpeRAD** [comment]
I would call spacing a preference, rather than optimization?

**Comment by Roemer** [comment]
I mean the small things like not needed else, property getters and such.

**Comment by Roemer** [comment]
So spacing changes is also a no-go?

**Comment by SharpeRAD** [comment]
Spacing never harmed anyone 😄

**Comment by Roemer** [comment]
Most modern static code analysis or linters fail if there are more than 1 blank line after each other.

**Comment by SharpeRAD** [comment]
Linting rules are optional...

**Comment by SharpeRAD** [comment]
I would love to accept a PR that adds functionality to the project but I feel this thread is really about personal preferences rather than optimizations.

**Comment by Roemer** [comment]
Is there anything you would agree to regarding existing code? Havent had a clear yes or no except for the regions. Please define your guidelines (I use default C#/ Resharper)

**Comment by SharpeRAD** [comment]
I would probably drop the additional indentation I added to regions, additional whitespace or explicit use of "else" never hurt anyone 😄

**Comment by SharpeRAD** [comment]
But again I think your focusing on the wrong thing as its not unreadable code. Multiple contributors have added to this project, so unless you have sever OCD I wouldn't get caught up on someone else's preferences...

**Comment by Roemer** [comment]
Ok, I won't bug you anymore with this. It's your decision.
I just want to mention some things you might reconsider:

1. Indentation
Indentation should always be done by the IDE. Never manually indent anyting. This makes sure that the indentation is always the same. If they differ from the default, provide a settings file (optimally a resharper file).

2. Readability
Code should be as easy and fast to read as possible.
Small example:
```csharp
//Security
string server = "";

if (settings is WebsiteSettings)
{
    server = "webServer";
}
else
{
    server = "ftpServer";
}

this.SetAuthentication(server, settings.Name, "", settings.Authentication);
this.SetAuthorization(server, settings.Name, "", settings.Authorization);
```
vs
```csharp
//Security
var server = settings is WebsiteSettings ? "webServer" : "ftpServer";
SetAuthentication(server, settings.Name, "", settings.Authentication);
SetAuthorization(server, settings.Name, "", settings.Authorization);
```
I thing it's pretty clear which one is easier and faster to read.
Another small one:
```csharp
/// <value>
/// <see cref="BindingProtocol"/> for <c>ftp</c> IIS binding type.
/// </value>
public static BindingProtocol Ftp
{
    get { return new BindingProtocol(Uri.UriSchemeFtp); }
}

/// <value>
/// <see cref="BindingProtocol"/> for <c>http</c> IIS binding type.
/// </value>
public static BindingProtocol Http
{
    get { return new BindingProtocol(Uri.UriSchemeHttp); }
}

/// <value>
/// <see cref="BindingProtocol"/> for <c>https</c> IIS binding type.
/// </value>
public static BindingProtocol Https
{
    get { return new BindingProtocol(Uri.UriSchemeHttps); }
}
```
vs
```csharp
/// <value>
/// <see cref="BindingProtocol"/> for <c>ftp</c> IIS binding type.
/// </value>
public static BindingProtocol Ftp => new BindingProtocol(Uri.UriSchemeFtp);

/// <value>
/// <see cref="BindingProtocol"/> for <c>http</c> IIS binding type.
/// </value>
public static BindingProtocol Http => new BindingProtocol(Uri.UriSchemeHttp);

/// <value>
/// <see cref="BindingProtocol"/> for <c>https</c> IIS binding type.
/// </value>
public static BindingProtocol Https => new BindingProtocol(Uri.UriSchemeHttps);
```

3. Regions (almost like religion :D)
Regions are a legacy construct (for generated code) and are usually not used anymore. The different "Types" inside a class (constructor, members, properties...) are always sorted the same (automatically).
There are some regions with are named wrongly because one just copy pastes them.
Also some regions do not even exist (so it is inconsistent).
These are some more reason not to keep them (e.g. in BaseManager, there are two constructor regions.
Also your regions have a ```(x)``` number at the end. Should this be a count? If so, it is often not correctly as you manually need to adjust them all the time.

4. Spacings
I just don't like to scroll more than needed. I use comments or other methods if you need to separate different code parts. Thats my personal opinion.

5. Resharper
Great tool, should be used by every C# developer. It usually is always right if it shows optimizations or warnings and you should follow them. Also it provides the ability to have a per project or per solution settings file which is automatically loaded (for formatting, naming, sorting and and and).

That's it. If you do feel that you want to reconsider anything from above I'd happily create a PR for that adjustments.

**Comment by SharpeRAD** [comment]
- I agree that regions are a legacy construct but I still love them and you're not going to change my Marmite view of them in a single PR.
- I agree that there are inconsistencies in the use of regions but it would have been better to fix them rather than remove them altogether, as it creates so much noise in your PR that [I can't see the wood for the trees](https://github.com/SharpeRAD/Cake.IIS/pull/30/files).
- I'd be happy to drop the count from the regions
- I like spacing, I find it helpful to focus.
- I don't have Resharper, its not free and I think its presumptuous to assume everyone has the budget for it. That said I should  start to use the new Roslyn code analysis packages as they are free and work with ruleset files that can be included in the solution. 

So yes, if you had just submitted a PR for the above changes without trying to change the overall style the PR's diff would have been focused and would have been accepted 😉
