### ISSUE TITLE
Setting authentication bug

### ISSUE THREAD

**Issue by ken-kamran** [SharpeRAD/Cake.IIS#32]
Cake.IIS code has bug when trying to set authentication settings. I have fixed the code and added tests but i can not push my changes, keep getting access denied. I can send you my changes if preferred. Thanks

**Comment by ken-kamran** [comment]
This is how BaseSiteManager now looks like,
`        protected void SetAuthentication(string server, string site, string appPath, AuthenticationSettings settings)
        {
            if (settings != null)
            {
                //Authentication
                var config = _Server.GetApplicationHostConfiguration();              
                var sectionName = "system." + server + "/security/authentication/{0}";
                  
                // Anonymous Authentication
                var anonymousAuthentication = config.GetSection(string.Format(sectionName, "anonymousAuthentication"), site);
                anonymousAuthentication["enabled"] = settings.EnableAnonymousAuthentication;
                _Log.Information("Anonymous Authentication enabled: {0}", settings.EnableAnonymousAuthentication);

                // Basic Authentication
                var basicAuthentication = config.GetSection(string.Format(sectionName, "basicAuthentication"), site);
                basicAuthentication["enabled"] = settings.EnableBasicAuthentication;
                _Log.Information("Basic Authentication enabled: {0}", settings.EnableBasicAuthentication);

                // Windows Authentication
                var windowsAuthentication = config.GetSection(string.Format(sectionName, "windowsAuthentication"), site);
                windowsAuthentication["enabled"] = settings.EnableWindowsAuthentication;
                _Log.Information("Windows Authentication enabled: {0}", settings.EnableWindowsAuthentication);
            }
            
        }`

**Comment by SharpeRAD** [comment]
You push to your own fork of the repository and then create a PR with the changes. Wait a day though as there's an outstanding PR I want to merge first.
