### ISSUE TITLE
Default values for ApplicationPoolSettings

### ISSUE THREAD

**Issue by amoerie** [SharpeRAD/Cake.IIS#37]
Hi! Thanks for the addin.

I did notice however that, when making an application pool, the settings default values (this is just the default values in C# for those properties, really) do not correspond with what IIS considers default settings.

Specifically, these settings are different:

- LoadUserProfile --> defaults to false in C#, defaults to true in IIS
- PingEnabled  --> defaults to false in C#, defaults to true in IIS
- MaximumWorkerProcesses -> defaults to 0 in C#, defaults to 1 in IIS. 

I believe it would be wiser to follow the defaults by IIS if possible.

**Comment by SharpeRAD** [comment]
Happy to accept a PR for this 😉

**Comment by amoerie** [comment]
Please see #38

**Comment by KoshelevS** [comment]
Just a note: `LoadUserProfile` parameter value is false by default in IIS deployed to Windows Server workstations.

**Comment by amoerie** [comment]
Slightly confusing this: the [official docs](https://docs.microsoft.com/en-us/iis/configuration/system.applicationHost/applicationPools/add/processModel) indicate that loadUserProfile indeed defaults to false, but some sample tests on various computers here at work show that it actually defaults to True. Maybe a registry setting somewhere which changes the default?

Not sure what the best option is here.

**Comment by SharpeRAD** [comment]
I've accepted the PR but changed LoadUserProfile to false to match the docs.
