### ISSUE TITLE
Problems with stopping/starting application pool

### ISSUE THREAD

**Issue by martinkotula** [SharpeRAD/Cake.IIS#43]
Hi,

First of all thanks for the addin ;)

We have some problems though with stopping and starting the application pool sometimes. The return value is true, there is a log message saying `Waiting for IIS to activate new config` but the pool is not successfully started/stopped.

Have you experienced any of this - any ideas what may be causing such behavior?

**Comment by SharpeRAD** [comment]
PR #41 may have solved this for you.
