### ISSUE TITLE
Could not load file or assembly 'System.Reflection.TypeExtensions

### ISSUE THREAD

**Issue by xaviervv** [SharpeRAD/Cake.IIS#46]
`Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified`

When I add the dll to tools\Addins\cake.iis\Cake.IIS\lib\net461 myself, the issue seems to be gone

**Comment by poindexter12** [comment]
+1

I'm getting this issue all over the place with 0.3.3. I pinned my version back to 0.3.1 and it works fine.

**Comment by xaviervv** [comment]
@poindexter12 Thanks that's a better solution than manipulating the reference myself for now.

**Comment by SharpeRAD** [comment]
Yes, don't think I should have #44.

**Comment by TerraVenil** [comment]
@xaviervv, @poindexter12 could you provide additional information regarding your environment that I able to reproduce current exception locally?

**Comment by xaviervv** [comment]
@TerraVenil 
Sorry for the late response. 

Developping on winodws 10 with vs 2017 and I have .net 4.7 sdk / run installed.
On build server (2012) I have msbuild tool for 2017 installed, with .net 4.7 sdk / runtime and webdeploy 3.6

This is my code regarding cake.iis
`#addin nuget:?package=Cake.IIS&version=0.3.1`

Remove &version=0.3.1

`var settings = GetIisApplicationSettings(_iisSiteName, _iisApplicationName, _iisApplicationPool, _iisPhysicalDir, null);
	var doesExists = SiteApplicationExists(settings);
	Information("Does application exist: " + doesExists);
	if(!doesExists){
		AddSiteApplication(settings);	
	}`

`private ApplicationSettings GetIisApplicationSettings(string site, string applicationName, string applicationPool, string physicalDirectory, string virtualDirectory){
	Information("site: " + site);
	Information("applicationName: " + applicationName);
	Information("applicationPool: " + applicationPool);
	Information("physicalDirectory: " + physicalDirectory);
	return new ApplicationSettings(){
		SiteName = site,
		ApplicationPath = "/" + applicationName,
		ApplicationPool = applicationPool,
		PhysicalDirectory = physicalDirectory,
		VirtualDirectory =  "/" + virtualDirectory
	};
}`

If you require more info. Please let me know.

**Comment by SharpeRAD** [comment]
This should be resolved by now with new releases
