### ISSUE TITLE
Update to work with cake 0.26.0

### ISSUE THREAD

**Issue by robbiecourtney** [SharpeRAD/Cake.IIS#47]
Please update Cake.IIS to support Cake.Core 0.26.0.

Error: The assembly 'Cake.IIS, Version=0.3.4.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.22.0).
This assembly need to reference at least Cake.Core version 0.26.0.

**Comment by SharpeRAD** [comment]
Resolved in v0.4.0
