### ISSUE TITLE
0.1.7 breaking changes for HostName/CreateWebsite?

### ISSUE THREAD

**Issue by blbu** [SharpeRAD/Cake.IIS#9]
Hi,

Thank you for providing this add-in -- it's very useful for us in our automated deployments.

However, I'm looking at failed deployments since version 0.1.7, in particular we have this Cake output:
error CS0117: 'Cake.IIS.WebsiteSettings' does not contain a definition for 'HostName'

The broken code looks something like:

CreateWebsite(new WebsiteSettings() {
            Name = siteDirectory,
            HostName = siteHostName,
            PhysicalDirectory = sitePhysicalPath,
            ApplicationPool = new ApplicationPoolSettings() {
                Name = siteApplicationPoolName
            }
        });

Would the recent bindings work be expected to completely break this?

**Comment by blbu** [comment]
We've updated our code to reflect your changes.

**Comment by SharpeRAD** [comment]
Sorry I think having separate binding settings is a good addition as it standardizes the AddBinding and AddWebsite methods but I should have updated the documentation to reflect the breaking changes.
